name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: product_service/requirements.txt


      - name: Docker info
        run: |
          docker --version
          docker info


      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r product_service/requirements.txt

      - name: Run tests
        run: |
          python3 -m pytest -v --junitxml=reports/junit.xml

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml
